package: cloud.lazycat.app.hello-algo
version: 1.3.0
name: Hello 算法
description: "动画图解、一键运行的数据结构与算法教程"
min_os_version: "1.5.0"
homepage: https://github.com/krahets/hello-algo
author: krahets
license: CC BY-NC-SA 4.0
locales:
  zh:
    name: Hello 算法
    description: "动画图解、一键运行的数据结构与算法教程"
  en:
    name: Hello Algo
    description: "Animated illustrations, one-click runnable data structures and algorithms tutorial"
